# Source: https://docs.travis-ci.com/user/languages/r
language: r
cache:
  apt: true
  packages: true
  timeout: 3000
addons:
  apt:
    packages:
      - default-jre
      - default-jdk
      - r-cran-rjava
script:
  - R CMD javareconf -e
r:
  - release
  - devel
bioc_required: true
use_bioc: true