# Source: https://docs.travis-ci.com/user/languages/r
language: r
cache:
  apt: true
  packages: true
  timeout: 3000
addons:
  apt:
    packages:
      - openjdk-9-jre
      - openjdk-9-jdk
      - openjdk-9-source
      - r-cran-rjava
r:
  - release
  - devel
bioc_required: true
use_bioc: true