#!/usr/bin/env Rscript

mran = "https://mran.microsoft.com/snapshot/2020-09-13"

# install dependencies
# copied from README, only those not available through conda
# most dependencies expressed in environment.yml
install.packages(
    c(
        "philentropy",
        "NetIndices"
    ),
    repos=mran
)

# no bioconductor packages are missing,
# but use this if any are added
# requireNamespace("BiocManager")
# BiocManager::install(...)
BiocManager::install(
    c(
        "impute"
    )
)

# install DIscBIO itself
# remotes::install_github("ocbe-uio/DIscBIO", "dev", repos=mran, build_vignettes=F)
devtools::install_local(getwd(), repos=mran)
