#!/usr/bin/env Rscript

mran = "https://mran.microsoft.com/snapshot/2020-09-13"

if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager", repos=mran)
}

# install dependencies
# copied from README, only those not available through conda
# most dependencies expressed in environment.yml
BiocManager::install(
    c(
        "philentropy", "imager", "NetIndices"
    )
)

# install DIscBIO itself
# remotes::install_github("ocbe-uio/DIscBIO", "dev", repos=mran, build_vignettes=F)
devtools::install_local(getwd(), repos=mran)
