#' @title Determining differentially expressed genes (DEGs) between all individual clusters.
#' @description This function defines DEGs between all individual clusters generated by either K-means or model based clustering. 
#' @param object \code{DISCBIO} class object.
#' @param Clustering Clustering has to be one of the following: ["K-means","MB"]. Default is "K-means"
#' @param K A numeric value of the number of clusters.
#' @param fdr A numeric value of the false discovery rate. Default is 0.05.
#' @param name A string vector showing the name to be used to save the resulted tables.
#' @param export A logical vector that allows writing the final gene list in excel file. Default is TRUE. 
#' @importFrom samr samr samr.compute.delta.table samr.plot samr.compute.siggenes.table
#' @importFrom graphics title
#' @importFrom utils write.csv
setGeneric("DEGanalysis", function(object,Clustering="K-means",K,fdr=0.05,name="Name",export = TRUE) standardGeneric("DEGanalysis"))

#' @export
#' @rdname DEGanalysis
setMethod("DEGanalysis",
          signature = "DISCBIO",
          definition = function(object,Clustering="K-means",K,fdr=0.05,name="Name",export = TRUE){
			if (!(Clustering %in% c( "K-means","MB"))) {
				stop("Clustering has to be either K-means or MB")
			}
			gene_list<-object@FinalGeneList
			gene_names<-rownames(object@expdata)
			idx_genes <- is.element(gene_names, gene_list)
			gene_names2 <- gene_names[idx_genes]
			dataset<- object@expdata[gene_names2,]
			Nam <-colnames(dataset)
			if (Clustering == "K-means") {
				Cluster_ID = object@cpart
				if ( length(object@cpart) < 1 ) stop("run Clustexp before running DEGanalysisM")
			}	

			if (Clustering == "MB") {
				Cluster_ID = object@MBclusters$clusterid
				if ( length(object@MBclusters$clusterid) < 1 ) stop("run ExprmclustMB before running DEGanalysisM")
				
			}	
			num<-c(1:K)
			num1<- paste("CL", num, sep="")
			for (n in num){
				Nam<-ifelse((Cluster_ID==n),num1[n],Nam)
			}
			colnames(dataset)<-Nam
			cat("The dataset is ready for differential expression analysis")
			num1<- paste("CL", num, sep="")
			clustName<- paste("Cl", num, sep="")
			ClusterLength<-c()
			for (i in num){
				d1<-clustName[i]
				d2<-dataset[,which(names(dataset)==num1[i])]
				ClusterLength[i]<-length(d2)
				assign(d1,d2)
			}
			ccdf<-data.frame(clustName,ClusterLength)
			ccdff<-ccdf[order(ClusterLength),] 
			clustName<-ccdff[,1]
			print(clustName)
			first<-c()
			second<-c()
			if ( K<2 ){
				stop( "K has to be at least 2" )
			}else if (K==2){
				first<-c(paste0(clustName[1]))
				second<-c(paste0(clustName[2]))

			}else if ( K==3 ){
				first<-c(rep(paste0(clustName[1]),2),rep(paste0(clustName[2]),1))
				second<-c(paste0(clustName[2]),paste0(clustName[3]),paste0(clustName[3]))
			}else if (K==4){
				first<-c(rep(paste0(clustName[1]),3),rep(paste0(clustName[2]),1),rep(paste0(clustName[4]),1),rep(paste0(clustName[3]),1))
				second<-c(paste0(clustName[2]),paste0(clustName[3]),paste0(clustName[4]),paste0(clustName[3]),paste0(clustName[2]),paste0(clustName[4]))
			}else if (K==5){
				first<-c(rep(paste0(clustName[1]),4),rep(paste0(clustName[2]),3),rep(paste0(clustName[3]),2),rep(paste0(clustName[5]),1))
				second<-c(paste0(clustName[2]),paste0(clustName[3]),paste0(clustName[4]),paste0(clustName[5]),paste0(clustName[3]),paste0(clustName[4]),paste0(clustName[5]),paste0(clustName[4]),paste0(clustName[5]),paste0(clustName[4]))
			}else if (K==6){
				first<-c(rep(paste0(clustName[1]),3),rep(paste0(clustName[5]),1),rep(paste0(clustName[1]),1),rep(paste0(clustName[2]),2),rep(paste0(clustName[5]),1),rep(paste0(clustName[2]),1),rep(paste0(clustName[3]),1),rep(paste0(clustName[5]),1),rep(paste0(clustName[3]),1),rep(paste0(clustName[5]),1),rep(paste0(clustName[4]),1),rep(paste0(clustName[5]),1))
				second<-c(paste0(clustName[2]),paste0(clustName[3]),paste0(clustName[4]),paste0(clustName[1]),paste0(clustName[6]),paste0(clustName[3]),paste0(clustName[4]),paste0(clustName[2]),paste0(clustName[6]),paste0(clustName[4]),paste0(clustName[3]),paste0(clustName[6]),paste0(clustName[4]),paste0(clustName[6]),paste0(clustName[6]))
			}
			o<-c(1:K)
			oo<-o[-length(o)]
			com<-sum(oo)
			cat("Number of comparisons: ", com *2,"\n")
			comNUM<-paste("comp", c(1:com), sep="")
			DEGsTable<-data.frame()
			DEGsE<-c()
			DEGsS<-c()
			for (i in 1:com){
				FinalDEGsL<-data.frame()
				FinalDEGsU<-data.frame()
				FDRl<-c()
				FDRu<-c()

				d1<-comNUM[i]
				d2<-cbind(get(first[i]), get(second[i]))
				assign(d1,d2)
				len<-c(length(get(first[i])[1,]),length(get(second[i])[1,]))
				y <- c(rep(1:2,len))
				L<-as.matrix(get(comNUM[i]))
				gname<-rownames(get(comNUM[i]))
				x<-L
				data=list(x=x,y=y, geneid=gname)
				samr.obj<-samr(data, resp.type="Two class unpaired", assay.type="seq",nperms=100,nresamp=20,testStatistic="wilcoxon",random.seed=15) #TODO: check if hangs for CV>.4 on test data?
				delta.table <- samr.compute.delta.table(samr.obj)
        
				wm<-which.min(delta.table[,5])
				if (delta.table[wm,5]<=fdr){
					w<-which(delta.table[,5]<= fdr)
					delta<-delta.table[w[1],1]-0.001
    
					samr.plot(samr.obj, delta)
					title(paste0("DEGs in the ",second[i]," in ",first[i]," VS ",second[i]))
    				siggenes.table<-samr.compute.siggenes.table(samr.obj,delta, data, delta.table)
        			FDRl<-as.numeric(siggenes.table$genes.lo[,8])/100
					FDRu<-as.numeric(siggenes.table$genes.up[,8])/100

					siggenes.table$genes.lo[,8]<- FDRl
					siggenes.table$genes.up[,8]<- FDRu
    
					DEGsTable[i,1]<-paste0(first[i]," VS ",second[i])
					DEGsTable[i,2]<-second[i]
					DEGsTable[i,3]<-length(FDRu)
					DEGsTable[i,4]<-paste0("Up-regulated-",name,second[i],"in",first[i],"VS",second[i],".csv")
					DEGsTable[i,5]<-length(FDRl)
					DEGsTable[i,6]<-paste0("Low-regulated-",name,second[i],"in",first[i],"VS",second[i],".csv")

					DEGsTable[i+com,1]<-paste0(first[i]," VS ",second[i])
					DEGsTable[i+com,2]<-first[i]
					DEGsTable[i+com,3]<-length(FDRu)
					DEGsTable[i+com,4]<-paste0("Low-regulated-",name,first[i],"in",first[i],"VS",second[i],".csv")
					DEGsTable[i+com,5]<-length(FDRl)
					DEGsTable[i+com,6]<-paste0("Up-regulated-",name,first[i],"in",first[i],"VS",second[i],".csv")
    
					if (length(FDRl)>0){
						mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
						genes <- siggenes.table$genes.lo[,3]
						G_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id","hgnc_symbol"),values=genes,mart= mart)
						FinalDEGsL<-cbind(genes,siggenes.table$genes.lo)
						FinalDEGsL<-merge(FinalDEGsL,G_list,by.x="genes",by.y="ensembl_gene_id")
						FinalDEGsL[,3]<-FinalDEGsL[,10]
						FinalDEGsL<-FinalDEGsL[,c(-1,-10)]
						FinalDEGsL<-FinalDEGsL[order(FinalDEGsL[,8]),]
						cat(paste0("Low-regulated genes in the ",second[i]," in ",first[i]," VS ",second[i],"\n"))
						write.csv(FinalDEGsL, file = paste0("Low-regulated-",name,second[i],"in",first[i],"VS",second[i],".csv"))
						write.csv(FinalDEGsL, file = paste0("Up-regulated-",name,first[i],"in",first[i],"VS",second[i],".csv"))
					
						DEGsS<-c(DEGsS,FinalDEGsL[,2])
						DEGsE<-c(DEGsE,as.character(FinalDEGsL[,3]))
					}
    
					if (length(FDRu)>0){
						mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
						genes <- siggenes.table$genes.up[,3]
						G_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id","hgnc_symbol"),values=genes,mart= mart)
						FinalDEGsU<-cbind(genes,siggenes.table$genes.up)
						FinalDEGsU<-merge(FinalDEGsU,G_list,by.x="genes",by.y="ensembl_gene_id")
						FinalDEGsU[,3]<-FinalDEGsU[,10]
						FinalDEGsU<-FinalDEGsU[,c(-1,-10)]
						FinalDEGsU<-FinalDEGsU[order(FinalDEGsU[,8]),]
						cat(paste0("Up-regulated genes in the ",second[i]," in ",first[i]," VS ",second[i],"\n"))
        
						write.csv(FinalDEGsU, file = paste0("Up-regulated-",name,second[i],"in",first[i],"VS",second[i],".csv"))
						write.csv(FinalDEGsU, file = paste0("Low-regulated-",name,first[i],"in",first[i],"VS",second[i],".csv"))
						DEGsS<-c(DEGsS,FinalDEGsU[,2])
						DEGsE<-c(DEGsE,as.character(FinalDEGsU[,3]))
					}

				}else{	
					DEGsTable[i,1]<-paste0(first[i]," VS ",second[i])
					DEGsTable[i,2]<-second[i]
					DEGsTable[i,3]<-NA
					DEGsTable[i,4]<-NA
					DEGsTable[i,5]<-NA
					DEGsTable[i,6]<-NA

					DEGsTable[i+com,1]<-paste0(first[i]," VS ",second[i])
					DEGsTable[i+com,2]<-first[i]
					DEGsTable[i+com,3]<-NA
					DEGsTable[i+com,4]<-NA
					DEGsTable[i+com,5]<-NA
					DEGsTable[i+com,6]<-NA
				}
			}
			cat("The results of DEGs are saved in your directory","\n")
			colnames(DEGsTable)<-c("Comparisons","Target cluster","Up-regulated genes","File name","Low-regulated genes","File name")
			write.csv(DEGsTable, file = "DEGsTable.csv")
			print(DEGsTable)
			sigDEG<-cbind(DEGsE,DEGsS)
			write.csv(sigDEG, file = "sigDEG.csv")
			return(list(sigDEG,DEGsTable))
})